# .rubocop.yml

# Set the target Ruby version
# Change this to the appropriate Ruby version for your project
AllCops:
  TargetRubyVersion: 3.1.2

# Enable cops and set their parameters as needed
# You can add more cops and configure them according to your project's needs
# Learn more about available cops and their parameters in the RuboCop documentation

# Layout/LineLength - Enforce a maximum line length
Layout/LineLength:
  Enabled: true
  Max: 120000 # Adjust the maximum line length as needed

# Style/Documentation - Ensure documentation comments are present
Style/Documentation:
  Enabled: false
Security/Open:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10000

Metrics/PerceivedComplexity:
  Max: 10000
Lint/IneffectiveAccessModifier:
  Enabled: false

# Naming/FileName - Enforce consistent file naming conventions
Naming/FileName:
  Enabled: true
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 2500

Metrics/MethodLength:
  Max: 3000
  Security/Open:
  Enabled: false
# Metrics/BlockLength - Limit the number of lines in a block
Metrics/BlockLength:
  Enabled: true
  Max: 100000 # Adjust the maximum block length as needed

# Other cops and their configurations...

# For more available cops and their configurations, refer to the RuboCop documentation:
# https://docs.rubocop.org/rubocop/cops.html
